using Bam.DependencyInjection;
using Bam.Generators.Decorators.Tests.Fixtures;
using Bam.Test;
using HandlebarsDotNet;
using NSubstitute;

namespace Bam.Generators.Decorators.Tests.Unit
{
    [UnitTestMenu("HandlebarsDecoratorCodeWriter Should", Selector = "hdcws")]
    public class HandlebarsDecoratorCodeWriterShould : UnitTestMenuContainer
    {
        public HandlebarsDecoratorCodeWriterShould(ServiceRegistry serviceRegistry) : base(serviceRegistry)
        {
        }

        private const string FixtureNamespace = "global::Bam.Generators.Decorators.Tests.Fixtures";

        internal static HandlebarsDecoratorCodeWriter RealWriter()
        {
            // Directory source points at an empty directory so only the embedded templates apply.
            string empty = Path.Combine(Path.GetTempPath(), "bam-decorator-templates-empty");
            return new HandlebarsDecoratorCodeWriter(
                new HandlebarsDirectory(empty),
                new HandlebarsEmbeddedResources(typeof(DecoratorModel).Assembly));
        }

        [UnitTest]
        public void RenderADecoratorFromEmbeddedTemplates()
        {
            After.Setup(reg =>
            {
                reg.For<HandlebarsDecoratorCodeWriter>().Use(RealWriter());
            })
            .When<HandlebarsDecoratorCodeWriter>("renders a decorator", writer =>
            {
                return new SourceOutcome(writer.GetSource(new DecoratorModel(typeof(IEchoService), typeof(EchoService))));
            })
            .TheTest
            .ShouldPass<SourceOutcome>((because, outcome) =>
            {
                string source = outcome.Source;
                because.ItsTrue("marks the file as generated", source.StartsWith("// <auto-generated>"));
                because.ItsTrue("declares the namespace", source.Contains("namespace Bam.Generators.Decorators.Tests.Fixtures.Decorators"));
                because.ItsTrue("declares the decorator class", source.Contains("public partial class EchoServiceDecorator : "));
                because.ItsTrue("extends the decorator base", source.Contains($": global::Bam.Generators.Decorators.Decorator<{FixtureNamespace}.IEchoService, {FixtureNamespace}.EchoService>, {FixtureNamespace}.IEchoService"));
                because.ItsTrue("takes the instance and a logger", source.Contains($"public EchoServiceDecorator({FixtureNamespace}.EchoService instance, global::Bam.Logging.ILogger? logger = null) : base(instance, logger)"));
                because.ItsTrue("routes the method through Intercept", source.Contains("return base.Intercept<global::System.String>(\"Message\", new object?[] { message }, () => "));
                because.ItsTrue("forwards to the decorated instance", source.Contains($"(({FixtureNamespace}.IEchoService)base.Instance).Message(message)"));
                because.ItsTrue("declares the extensions class", source.Contains("public static partial class EchoServiceDecoratorExtensions"));
                because.ItsTrue("emits the decorate extension", source.Contains("DecorateEchoService(this global::Bam.DependencyInjection.ServiceRegistry registry"));
                because.ItsTrue("emits a hook for each phase", source.Contains(" OnMessageStart(") && source.Contains(" OnMessageEnd(") && source.Contains(" OnMessageError("));
                because.ItsTrue("emits typed handlers", source.Contains("global::System.String?> handler"));
                because.ItsTrue("emits instance-level hooks", source.Contains($"OnMessageStart(this {FixtureNamespace}.IEchoService service"));
                because.ItsTrue("leaves no unrendered template syntax", !source.Contains("{{") && !source.Contains("}}"));
            })
            .SoBeHappy()
            .UnlessItFailed();
        }

        [UnitTest]
        public void RenderEveryMemberShape()
        {
            After.Setup(reg =>
            {
                reg.For<HandlebarsDecoratorCodeWriter>().Use(RealWriter());
            })
            .When<HandlebarsDecoratorCodeWriter>("renders a decorator for members of every shape", writer =>
            {
                return new SourceOutcome(writer.GetSource(new DecoratorModel(typeof(IKitchenSinkService), typeof(KitchenSinkService))));
            })
            .TheTest
            .ShouldPass<SourceOutcome>((because, outcome) =>
            {
                string source = outcome.Source;
                string target = $"(({FixtureNamespace}.IKitchenSinkService)base.Instance)";
                because.ItsTrue("forwards a read-only property", source.Contains($"get => {target}.Count;"));
                because.ItsTrue("forwards an indexer", source.Contains("public global::System.String this[global::System.Int32 index]") && source.Contains($"set => {target}[index] = value;"));
                because.ItsTrue("forwards an inherited property through its own interface", source.Contains($"(({FixtureNamespace}.INamedService)base.Instance).Name = value;"));
                because.ItsTrue("forwards an event", source.Contains("public event global::System.EventHandler? Changed") && source.Contains($"add => {target}.Changed += value;"));
                because.ItsTrue("intercepts a void method", source.Contains($"base.Intercept(\"Reset\", global::System.Array.Empty<object?>(), () => {target}.Reset()).ThrowIfFailed();"));
                because.ItsTrue("awaits a Task<T> method", source.Contains("public async global::System.Threading.Tasks.Task<global::System.Int32> AddAsync(") && source.Contains("(await base.InterceptAsync<global::System.Int32>(\"AddAsync\""));
                because.ItsTrue("awaits a Task method", source.Contains("(await base.InterceptAsync(\"ResetAsync\""));
                because.ItsTrue("converts a ValueTask<T> to a task", source.Contains(".DescribeAsync(subject).AsTask()"));
                because.ItsTrue("converts a ValueTask to a task", source.Contains(".FlushAsync().AsTask()"));
                because.ItsTrue("forwards a method with an out parameter untouched", source.Contains($"return {target}.TryParse(text, out value);"));
                because.ItsTrue("implements a generic method explicitly", source.Contains($"TItem {FixtureNamespace}.IKitchenSinkService.Echo<TItem>(TItem item)"));
                because.ItsTrue("implements a colliding name explicitly and escapes keywords", source.Contains($"global::System.String {FixtureNamespace}.IKitchenSinkService.Invoke(global::System.String @event)"));
                because.ItsTrue("keeps nullable annotations", source.Contains("public global::System.String? Find(global::System.String? key)"));
                because.ItsTrue("emits no typed handler where overloads disagree", !source.Contains("OnAddStart(this global::Bam.DependencyInjection.ServiceRegistry registry, global::System.Func"));
                because.ItsTrue("emits no hooks for a forwarded method", !source.Contains("OnTryParse"));
            })
            .SoBeHappy()
            .UnlessItFailed();
        }

        [UnitTest]
        public void WriteTheSourceToAStream()
        {
            After.Setup(reg =>
            {
                reg.For<HandlebarsDecoratorCodeWriter>().Use(RealWriter());
            })
            .When<HandlebarsDecoratorCodeWriter>("writes a decorator to a stream", writer =>
            {
                DecoratorModel model = new DecoratorModel(typeof(IEchoService), typeof(EchoService));
                using MemoryStream stream = new MemoryStream();
                writer.WriteDecorator(model, stream);
                bool stillOpen = stream.CanWrite;
                stream.Position = 0;
                using StreamReader reader = new StreamReader(stream);
                return new StreamOutcome(reader.ReadToEnd() == writer.GetSource(model), stillOpen);
            })
            .TheTest
            .ShouldPass<StreamOutcome>((because, outcome) =>
            {
                because.ItsTrue("the stream holds the rendered source", outcome.MatchesSource);
                because.ItsTrue("the stream is left open for the caller", outcome.LeftOpen);
            })
            .SoBeHappy()
            .UnlessItFailed();
        }

        [UnitTest]
        public void RenderWithoutADirectorySource()
        {
            After.Setup(reg =>
            {
                reg.For<HandlebarsDecoratorCodeWriter>().Use(HandlebarsDecoratorCodeWriter.EmbeddedOnly());
            })
            .When<HandlebarsDecoratorCodeWriter>("has only the embedded templates", writer =>
            {
                DecoratorModel model = new DecoratorModel(typeof(IEchoService), typeof(EchoService));
                return new EmbeddedOutcome(writer.HandlebarsDirectory == null, writer.GetSource(model) == RealWriter().GetSource(model));
            })
            .TheTest
            .ShouldPass<EmbeddedOutcome>((because, outcome) =>
            {
                because.ItsTrue("it has no directory source", outcome.HasNoDirectory);
                because.ItsTrue("it renders the same source as a writer with an empty directory", outcome.RendersTheSame);
            })
            .SoBeHappy()
            .UnlessItFailed();
        }

        [UnitTest]
        public void UseATemplateThatStandsAlone()
        {
            // Handlebars partials are registered process-wide, so a template that referenced one could be
            // changed by whatever any other generator loaded. The decorator template must reference none.
            When.A<HandlebarsDecoratorCodeWriterShould>("reads the embedded templates", this, test =>
            {
                System.Reflection.Assembly assembly = typeof(HandlebarsDecoratorCodeWriter).Assembly;
                string[] templates = assembly.GetManifestResourceNames().Where(name => name.EndsWith(".hbs")).ToArray();
                bool referencesPartial = templates.Any(name =>
                {
                    using StreamReader reader = new StreamReader(assembly.GetManifestResourceStream(name)!);
                    return reader.ReadToEnd().Contains("{{>");
                });
                return new TemplateOutcome(string.Join(",", templates.Select(name => name.Substring(name.LastIndexOf("Templates.")))), referencesPartial);
            })
            .TheTest
            .ShouldPass<TemplateOutcome>((because, outcome) =>
            {
                because.ItsTrue("there is one embedded template", outcome.Templates == "Templates.Decorator.hbs", outcome.Templates);
                because.ItsTrue("it references no partials", !outcome.ReferencesPartial);
            })
            .SoBeHappy()
            .UnlessItFailed();
        }

        [UnitTest]
        public void ReloadBothTemplateSourcesOnLoad()
        {
            IHandlebarsDirectory directory = Substitute.For<IHandlebarsDirectory>();
            IHandlebarsEmbeddedResources embedded = Substitute.For<IHandlebarsEmbeddedResources>();

            After.Setup(reg =>
            {
                reg.For<HandlebarsDecoratorCodeWriter>().Use(new HandlebarsDecoratorCodeWriter(directory, embedded));
            })
            .When<HandlebarsDecoratorCodeWriter>("loads twice", writer =>
            {
                writer.Load();
                writer.Load();
                return new ReloadOutcome(
                    directory.ReceivedCalls().Count(call => call.GetMethodInfo().Name == nameof(IHandlebarsDirectory.Reload)),
                    embedded.ReceivedCalls().Count(call => call.GetMethodInfo().Name == nameof(IHandlebarsEmbeddedResources.Reload)));
            })
            .TheTest
            .ShouldPass<ReloadOutcome>((because, outcome) =>
            {
                because.ItsTrue("the directory source is reloaded once", outcome.DirectoryReloads == 1);
                because.ItsTrue("the embedded source is reloaded once", outcome.EmbeddedReloads == 1);
            })
            .SoBeHappy()
            .UnlessItFailed();
        }

        [UnitTest]
        public void PreferATemplateFromTheDirectory()
        {
            IHandlebarsDirectory directory = Substitute.For<IHandlebarsDirectory>();
            directory.Templates.Returns(new Dictionary<string, Func<object, string>>
            {
                { HandlebarsDecoratorCodeWriter.TemplateName, model => "// overridden" }
            });
            directory.Render(HandlebarsDecoratorCodeWriter.TemplateName, Arg.Any<object>()).Returns("// overridden");
            IHandlebarsEmbeddedResources embedded = Substitute.For<IHandlebarsEmbeddedResources>();

            After.Setup(reg =>
            {
                reg.For<HandlebarsDecoratorCodeWriter>().Use(new HandlebarsDecoratorCodeWriter(directory, embedded));
            })
            .When<HandlebarsDecoratorCodeWriter>("has a directory template of the same name", writer =>
            {
                return new SourceOutcome(writer.GetSource(new DecoratorModel(typeof(IEchoService), typeof(EchoService))));
            })
            .TheTest
            .ShouldPass<SourceOutcome>((because, outcome) =>
            {
                because.ItsTrue("the directory template wins", outcome.Source == "// overridden");
            })
            .SoBeHappy()
            .UnlessItFailed();
        }

        [UnitTest]
        public void FailWhenTheTemplateIsMissing()
        {
            IHandlebarsDirectory directory = Substitute.For<IHandlebarsDirectory>();
            directory.Templates.Returns(new Dictionary<string, Func<object, string>>());
            IHandlebarsEmbeddedResources embedded = Substitute.For<IHandlebarsEmbeddedResources>();
            embedded.Templates.Returns(new Dictionary<string, HandlebarsTemplate<object, object>>());

            After.Setup(reg =>
            {
                reg.For<HandlebarsDecoratorCodeWriter>().Use(new HandlebarsDecoratorCodeWriter(directory, embedded));
            })
            .When<HandlebarsDecoratorCodeWriter>("has no template in either source", writer =>
            {
                try
                {
                    return new SourceOutcome(writer.GetSource(new DecoratorModel(typeof(IEchoService), typeof(EchoService))));
                }
                catch (InvalidOperationException ex)
                {
                    return new SourceOutcome("threw: " + ex.Message);
                }
            })
            .TheTest
            .ShouldPass<SourceOutcome>((because, outcome) =>
            {
                because.ItsTrue("it throws naming the template", outcome.Source == "threw: Decorator template 'Decorator' not found.", outcome.Source);
            })
            .SoBeHappy()
            .UnlessItFailed();
        }

        private sealed record SourceOutcome(string Source);

        private sealed record EmbeddedOutcome(bool HasNoDirectory, bool RendersTheSame);

        private sealed record TemplateOutcome(string Templates, bool ReferencesPartial);

        private sealed record StreamOutcome(bool MatchesSource, bool LeftOpen);

        private sealed record ReloadOutcome(int DirectoryReloads, int EmbeddedReloads);
    }
}
